import type { Metadata } from "next"
import { Plus_Jakarta_Sans } from "next/font/google"
import "@/app/globals.css"
import Modal from "@/components/modal"

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  display: 'swap',
  variable: '--font-plus-jakarta',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={plusJakarta.className}>
      <body className="antialiased relative">
        {children}
        <footer className="bg-white h-20 flex items-center justify-center text-center text-gray-800 text-sm font-semibold">
          <p>Designer: Kevin || Developer: Victren</p>
        </footer>
        <Modal initialIsOpen={false} />
      </body>
    </html>
  )
}
