import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "/app/globals.css";
import NavigationBar from "app/dashboard/topNavigationBar";
// import MainNavigationBar from "@/components/sideNavigationBar"
import SessionProviderWrapper from "@/components/sessionproviderwrapper";
import { Toaster } from "sonner";
import { Suspense } from "react";
import DashboardSkeleton from "@/components/Dashboard Skeleton UI/DashboardSkeleton";

const plusJakarta = Plus_Jakarta_Sans({
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600", "700", "800"],
    display: "swap",
    variable: "--font-plus-jakarta",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={plusJakarta.className}>
            <body className="antialiased relative flex h-screen">
                {/* <MainNavigationBar /> */}
                <main className=" w-full overflow-y-auto bg-[var(--background-bg)]">
                    <NavigationBar />
                    <SessionProviderWrapper>
                        <Suspense fallback={<DashboardSkeleton />}>{children}</Suspense>
                    </SessionProviderWrapper>
                </main>
                <Toaster position="top-center" expand={false} richColors closeButton />
            </body>
        </html>
    );
}
